-- LOTRO Events - localization
-- Supported LOTRO client languages: English, English (UK), French, German.
-- Unknown/deprecated client languages fall back to English.

DuskLOTROEvents = DuskLOTROEvents or {};

DuskLOTROEvents.Localization = {
    en = {
        activeHeader = "ACTIVE EVENTS",
        upcomingHeader = "UPCOMING EVENTS — %d DAYS",
        noticesHeader = "DATES TO REMEMBER — %d DAYS",
        noActive = "No event is currently active.",
        noUpcoming = "No event starts in the next %d days.",
        starts = "Starts:",
        ends = "Ends:",
        dateLabel = "Date:",
        approximateDate = "Approx. date:",
        inWord = "in",
        close = "Close",
        shortHelp = "Opens the LOTRO Events window.",
        longHelp = "%s opens the LOTRO Events window.",
        lessThanMinute = "less than 1 min",
        day = "d",
        hour = "h",
        minute = "min",
        listTab = "List",
        calendarTab = "Calendar",
        today = "Today",
        weekdayHeaders = { "Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun" },
        monthNames = { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" },
        optionsGeneral = "GENERAL",
        optionsList = "LIST",
        optionsCalendar = "CALENDAR",
        optionsWindow = "WINDOW",
        optionsTimeZone = "TIME ZONE",
        optionsMaintenance = "MAINTENANCE",
        optionLauncherVisible = "Show plugin icon",
        optionLauncherLocked = "Lock launcher position",
        optionLauncherLockedCompact = "Lock launcher",
        optionResetLauncher = "Reset launcher position",
        optionResetLauncherCompact = "Reset launcher",
        optionDefaultView = "Default view",
        optionRememberLastView = "Remember last view used",
        optionRememberLastViewCompact = "Remember last view",
        optionChatAnnounce = "Announce active events in chat at startup",
        optionChatAnnounceCompact = "Announce active events",
        optionChatAnnounceLongEvents = "Include long events (> %d days) in chat",
        optionChatAnnounceLongEventsCompact = "Include long events (> %d d)",
        chatActiveOne = "1 active event:",
        chatActiveMany = "%d active events:",
        optionUpcomingDays = "Upcoming events",
        optionShowActive = "Show active events",
        optionShowNotices = "Show notices / special dates",
        optionShowNoticesCompact = "Show notices",
        optionShowDuration = "Show 'in X d X h'",
        optionHideLongEvents = "Hide events longer than %d days",
        optionHideLongEventsCompact = "Hide events > %d days",
        optionWeekStart = "First day of week",
        weekStartMonday = "Monday",
        weekStartSunday = "Sunday",
        optionCalendarLongEvents = "Show long events",
        optionDifferentColors = "Different color for each event",
        optionDifferentColorsCompact = "One color per event",
        optionWindowSize = "Window size",
        windowSizeNormal = "Normal",
        windowSizeLarge = "Large",
        optionRememberWindowPosition = "Remember window position",
        optionRememberWindowPositionCompact = "Remember position",
        optionCenterWindow = "Center window",
        optionResetWindow = "Reset size and position",
        optionResetWindowCompact = "Reset size/position",
        optionTimeZone = "Displayed time",
        timeZoneAuto = "Auto (client language)",
        timeZoneServer = "LOTRO server",
        timeZoneEurope = "Europe",
        timeZoneUK = "United Kingdom",
        optionResetAll = "Reset all settings",
        optionResetAllCompact = "Reset settings",
        optionConfirmResetAll = "Click again to confirm",
        saveFailed = "Unable to save settings:",
        settingsLoadFailed = "Unable to load saved settings; default values are being used and the unreadable settings will not be overwritten automatically.",
        openFailed = "Unable to open the LOTRO Events window:",
        commandRegistrationFailed = "Unable to register /events or /lotroevents.",
        commandEventsUnavailable = "/events is already used by another plugin; use /lotroevents for LOTRO Events.",
        commandUnavailable = "Both /events and /lotroevents are already used by another plugin.",
        displaySizeListenerFailed = "Display-resolution monitoring could not be initialized; automatic UI repositioning after a resolution change is disabled.",
        calendarCoverageExpiring = "The embedded event calendar will soon need an update; its latest known entry ends on %s.",
        calendarCoverageExpired = "The embedded event calendar is out of date; its latest known entry ended on %s.",
        daysWord = "days",
    },

    fr = {
        activeHeader = "ÉVÉNEMENTS ACTIFS",
        upcomingHeader = "PROCHAINS ÉVÉNEMENTS — %d JOURS",
        noticesHeader = "DATES À RETENIR — %d JOURS",
        noActive = "Aucun événement actif actuellement.",
        noUpcoming = "Aucun événement ne commence dans les %d prochains jours.",
        starts = "Début :",
        ends = "Fin :",
        dateLabel = "Date :",
        approximateDate = "Date approximative :",
        inWord = "dans",
        close = "Fermer",
        shortHelp = "Ouvre la fenêtre LOTRO Events.",
        longHelp = "%s ouvre la fenêtre LOTRO Events.",
        lessThanMinute = "moins d'1 min",
        day = "j",
        hour = "h",
        minute = "min",
        listTab = "Liste",
        calendarTab = "Calendrier",
        today = "Aujourd'hui",
        weekdayHeaders = { "Lun", "Mar", "Mer", "Jeu", "Ven", "Sam", "Dim" },
        monthNames = { "Janvier", "Février", "Mars", "Avril", "Mai", "Juin", "Juillet", "Août", "Septembre", "Octobre", "Novembre", "Décembre" },
        optionsGeneral = "GÉNÉRAL",
        optionsList = "LISTE",
        optionsCalendar = "CALENDRIER",
        optionsWindow = "FENÊTRE",
        optionsTimeZone = "FUSEAU HORAIRE",
        optionsMaintenance = "MAINTENANCE",
        optionLauncherVisible = "Afficher l'icône du plugin",
        optionLauncherLocked = "Verrouiller la position de l'icône",
        optionLauncherLockedCompact = "Verrouiller l'icône",
        optionResetLauncher = "Réinitialiser la position de l'icône",
        optionResetLauncherCompact = "Réinitialiser l'icône",
        optionDefaultView = "Vue par défaut",
        optionRememberLastView = "Mémoriser la dernière vue utilisée",
        optionRememberLastViewCompact = "Mémoriser la dernière vue",
        optionChatAnnounce = "Annonce chat des événements actifs au chargement",
        optionChatAnnounceCompact = "Annoncer les événements actifs",
        optionChatAnnounceLongEvents = "Inclure les événements longs (> %d j) dans le chat",
        optionChatAnnounceLongEventsCompact = "Inclure les longs (> %d j)",
        chatActiveOne = "1 événement actif :",
        chatActiveMany = "%d événements actifs :",
        optionUpcomingDays = "Événements à venir",
        optionShowActive = "Afficher les événements actifs",
        optionShowNotices = "Afficher les notices / dates ponctuelles",
        optionShowNoticesCompact = "Afficher les notices",
        optionShowDuration = "Afficher « dans X j X h »",
        optionHideLongEvents = "Masquer les événements de plus de %d jours",
        optionHideLongEventsCompact = "Masquer les > %d jours",
        optionWeekStart = "Premier jour de la semaine",
        weekStartMonday = "Lundi",
        weekStartSunday = "Dimanche",
        optionCalendarLongEvents = "Afficher les événements longs",
        optionDifferentColors = "Couleur différente par événement",
        optionDifferentColorsCompact = "Une couleur par événement",
        optionWindowSize = "Taille de la fenêtre",
        windowSizeNormal = "Normale",
        windowSizeLarge = "Grande",
        optionRememberWindowPosition = "Mémoriser la position de la fenêtre",
        optionRememberWindowPositionCompact = "Mémoriser position fenêtre",
        optionCenterWindow = "Recentrer la fenêtre",
        optionResetWindow = "Réinitialiser taille et position",
        optionResetWindowCompact = "Réinitialiser taille/position",
        optionTimeZone = "Heure affichée",
        timeZoneAuto = "Auto (langue client)",
        timeZoneServer = "Serveur LOTRO",
        timeZoneEurope = "Europe",
        timeZoneUK = "Royaume-Uni",
        optionResetAll = "Réinitialiser tous les réglages",
        optionResetAllCompact = "Réinitialiser les réglages",
        optionConfirmResetAll = "Cliquer encore pour confirmer",
        saveFailed = "Impossible de sauvegarder les réglages :",
        settingsLoadFailed = "Impossible de charger les réglages sauvegardés ; les valeurs par défaut sont utilisées et les réglages illisibles ne seront pas écrasés automatiquement.",
        openFailed = "Impossible d'ouvrir la fenêtre LOTRO Events :",
        commandRegistrationFailed = "Impossible d'enregistrer /events ou /lotroevents.",
        commandEventsUnavailable = "/events est déjà utilisé par un autre plugin ; utilise /lotroevents pour LOTRO Events.",
        commandUnavailable = "/events et /lotroevents sont déjà utilisés par un autre plugin.",
        displaySizeListenerFailed = "Impossible d'initialiser la surveillance des changements de résolution ; le repositionnement automatique de l'interface après un changement de résolution est désactivé.",
        calendarCoverageExpiring = "Le calendrier intégré devra bientôt être mis à jour ; sa dernière entrée connue se termine le %s.",
        calendarCoverageExpired = "Le calendrier intégré n'est plus à jour ; sa dernière entrée connue s'est terminée le %s.",
        daysWord = "jours",
    },

    de = {
        activeHeader = "AKTIVE EREIGNISSE",
        upcomingHeader = "KOMMENDE EREIGNISSE — %d TAGE",
        noticesHeader = "WICHTIGE TERMINE — %d TAGE",
        noActive = "Derzeit ist kein Ereignis aktiv.",
        noUpcoming = "In den nächsten %d Tagen beginnt kein Ereignis.",
        starts = "Beginn:",
        ends = "Ende:",
        dateLabel = "Datum:",
        approximateDate = "Ca. Datum:",
        inWord = "in",
        close = "Schließen",
        shortHelp = "Öffnet das LOTRO-Events-Fenster.",
        longHelp = "%s öffnet das LOTRO-Events-Fenster.",
        lessThanMinute = "unter 1 Min",
        day = "T",
        hour = "Std",
        minute = "Min",
        listTab = "Liste",
        calendarTab = "Kalender",
        today = "Heute",
        weekdayHeaders = { "Mo", "Di", "Mi", "Do", "Fr", "Sa", "So" },
        monthNames = { "Januar", "Februar", "März", "April", "Mai", "Juni", "Juli", "August", "September", "Oktober", "November", "Dezember" },
        optionsGeneral = "ALLGEMEIN",
        optionsList = "LISTE",
        optionsCalendar = "KALENDER",
        optionsWindow = "FENSTER",
        optionsTimeZone = "ZEITZONE",
        optionsMaintenance = "WARTUNG",
        optionLauncherVisible = "Plugin-Symbol anzeigen",
        optionLauncherLocked = "Position des Symbols sperren",
        optionLauncherLockedCompact = "Symbol sperren",
        optionResetLauncher = "Symbolposition zurücksetzen",
        optionResetLauncherCompact = "Symbol zurücksetzen",
        optionDefaultView = "Standardansicht",
        optionRememberLastView = "Letzte Ansicht merken",
        optionRememberLastViewCompact = "Letzte Ansicht merken",
        optionChatAnnounce = "Aktive Ereignisse beim Start im Chat",
        optionChatAnnounceCompact = "Aktive Ereignisse ankündigen",
        optionChatAnnounceLongEvents = "Lange Ereignisse (> %d Tage) im Chat",
        optionChatAnnounceLongEventsCompact = "Lange Ereignisse (> %d T)",
        chatActiveOne = "1 aktives Ereignis:",
        chatActiveMany = "%d aktive Ereignisse:",
        optionUpcomingDays = "Kommende Ereignisse",
        optionShowActive = "Aktive Ereignisse anzeigen",
        optionShowNotices = "Hinweise / besondere Daten anzeigen",
        optionShowNoticesCompact = "Hinweise anzeigen",
        optionShowDuration = "„in X T X Std“ anzeigen",
        optionHideLongEvents = "Ereignisse über %d Tage ausblenden",
        optionHideLongEventsCompact = "> %d Tage ausblenden",
        optionWeekStart = "Erster Wochentag",
        weekStartMonday = "Montag",
        weekStartSunday = "Sonntag",
        optionCalendarLongEvents = "Lange Ereignisse anzeigen",
        optionDifferentColors = "Unterschiedliche Farbe je Ereignis",
        optionDifferentColorsCompact = "Eine Farbe je Ereignis",
        optionWindowSize = "Fenstergröße",
        windowSizeNormal = "Normal",
        windowSizeLarge = "Groß",
        optionRememberWindowPosition = "Fensterposition merken",
        optionRememberWindowPositionCompact = "Fensterposition merken",
        optionCenterWindow = "Fenster zentrieren",
        optionResetWindow = "Größe und Position zurücksetzen",
        optionResetWindowCompact = "Größe/Position zurücksetzen",
        optionTimeZone = "Angezeigte Zeit",
        timeZoneAuto = "Auto (Client-Sprache)",
        timeZoneServer = "LOTRO-Server",
        timeZoneEurope = "Europa",
        timeZoneUK = "Vereinigtes Königreich",
        optionResetAll = "Alle Einstellungen zurücksetzen",
        optionResetAllCompact = "Einstellungen zurücksetzen",
        optionConfirmResetAll = "Zum Bestätigen erneut klicken",
        saveFailed = "Einstellungen konnten nicht gespeichert werden:",
        settingsLoadFailed = "Gespeicherte Einstellungen konnten nicht geladen werden; Standardwerte werden verwendet und die nicht lesbaren Einstellungen werden nicht automatisch überschrieben.",
        openFailed = "LOTRO-Events-Fenster konnte nicht geöffnet werden:",
        commandRegistrationFailed = "/events oder /lotroevents konnte nicht registriert werden.",
        commandEventsUnavailable = "/events wird bereits von einem anderen Plugin verwendet; nutze /lotroevents für LOTRO Events.",
        commandUnavailable = "/events und /lotroevents werden bereits von einem anderen Plugin verwendet.",
        displaySizeListenerFailed = "Die Überwachung von Auflösungsänderungen konnte nicht initialisiert werden; die automatische UI-Neupositionierung nach einem Auflösungswechsel ist deaktiviert.",
        calendarCoverageExpiring = "Der integrierte Ereigniskalender muss bald aktualisiert werden; der letzte bekannte Eintrag endet am %s.",
        calendarCoverageExpired = "Der integrierte Ereigniskalender ist veraltet; der letzte bekannte Eintrag endete am %s.",
        daysWord = "Tage",
    },
};

DuskLOTROEvents.EventNames = {
    hard_tack = {
        en = "Hard Tack Crafting Event",
        fr = "Événement d'artisanat Rations de marche",
        de = "Hartkeks-Handwerksereignis",
    },
    xp_25 = {
        en = "25% XP Boost",
        fr = "Bonus d'EXP de 25 %",
        de = "25 % EP-Bonus",
    },
    buried_treasure = {
        en = "Buried Treasure Event",
        fr = "Événement Trésor enfoui",
        de = "Ereignis \"Vergrabener Schatz\"",
    },
    crafting_xp_25 = {
        en = "25% Crafting XP",
        fr = "Bonus de 25 % sur l'EXP d'artisanat",
        de = "25 % Handwerks-EP-Bonus",
    },
    forester = {
        en = "Forester Crafting Event",
        fr = "Événement d'artisanat forestier",
        de = "Förster-Handwerksereignis",
    },
    virtue_10 = {
        en = "10% Virtue XP Boost",
        fr = "Bonus d'EXP de vertu de 10 %",
        de = "10 % Tugend-EP-Bonus",
    },
    lootbox_10 = {
        en = "10% Lootbox Embers/Motes bonus",
        fr = "Bonus de 10 % sur les coffres de braises/grains",
        de = "10 % Bonus auf Funken und Staub in Schatzkästchen",
    },
    hobnanigans = {
        en = "Hobnanigans",
        fr = "Chasse-poulet",
        de = "Hobnanigans",
    },
    vip_boost = {
        en = "VIP Event Boost",
        fr = "Bonus d'événement VIP",
        de = "VIP-Event-Bonus",
    },
    skirmish_25 = {
        en = "25% Skirmish Marks",
        fr = "Bonus de 25 % sur les marques d'escarmouche",
        de = "25 % Bonus auf Scharmützel-Zeichen",
    },
    li_season_17 = {
        en = "LI Reward Track Season 17",
        fr = "Saison 17 du suivi de récompense d'objets légendaires",
        de = "Belohnungsleiste für legendäre Gegenstände (Saison 17)",
    },
    spring_festival = {
        en = "Spring Festival",
        fr = "Festival du printemps",
        de = "Frühlingsfest",
    },
    lootbox_25 = {
        en = "25% Lootbox Embers/Motes bonus",
        fr = "Bonus de 25 % sur les coffres de braises/grains",
        de = "25 % Bonus auf Funken und Staub in Schatzkästchen",
    },
    april_fools_chicken = {
        en = "April Fool's Chicken Run",
        fr = "Poulet en fuite du 1er avril",
        de = "Hühnerrennen zum Aprilscherz",
    },
    anniversary_19 = {
        en = "Anniversary (19yrs!)",
        fr = "Anniversaire (19 ans !)",
        de = "Jubiläum (19 Jahre!)",
    },
    virtue_20 = {
        en = "20% Virtue XP Boost",
        fr = "Bonus d'EXP de vertu de 20 %",
        de = "20 % Tugend-EP-Bonus",
    },
    curator = {
        en = "Curator Returns - Figment vendor",
        fr = "Le conservateur est de retour (marchand de mirages)",
        de = "Die Kuratorin kehrt zurück - Prachtstück-Händlerin",
    },
    li_season_18 = {
        en = "LI Reward Track Season 18",
        fr = "Saison 18 du suivi de récompense d'objets légendaires",
        de = "Belohnungsleiste für legendäre Gegenstände (Saison 18)",
    },
    midsummer = {
        en = "Midsummer Festival",
        fr = "Festival du Solstice d'été",
        de = "Mittsommerfest",
    },
    ill_omens = {
        en = "Ill Omens Skirmish event",
        fr = "Événement d'escarmouche Mauvais présages",
        de = "Scharmützel-Ereignis \"Böse Omen\"",
    },
    farmers_faire = {
        en = "Farmers Faire",
        fr = "Foire des fermiers",
        de = "Bauernfest",
    },
    li_season_19 = {
        en = "LI Reward Track Season 19",
        fr = "Saison 19 du suivi de récompense d'objets légendaires",
        de = "Belohnungsleiste für legendäre Gegenstände (Saison 19)",
    },
    treasure_bugan = {
        en = "Treasure Bugan event",
        fr = "Événement du Trésor bugan",
        de = "Schatz-Bugan-Ereignis",
    },
    shipwrecked_mariners = {
        en = "Tale of the Shipwrecked Mariners",
        fr = "Le lai des marins naufragés",
        de = "Die Geschichte der schiffbrüchigen Seefahrer",
    },
    bilbo_birthday = {
        en = "Bilbo's Birthday",
        fr = "Anniversaire de Bilbon",
        de = "Beutlins Geburtstag",
    },
    harvestmath = {
        en = "Harvestmath (Fall) Festival",
        fr = "Le Festival des Moissines (d'automne)",
        de = "Erntefest (Herbst)",
    },
    durins_day = {
        en = "Durin's Day event",
        fr = "Événement Le Jour de Durin",
        de = "Durinstag-Ereignis",
    },
    li_season_20 = {
        en = "LI Reward Track Season 20",
        fr = "Saison 20 du suivi de récompense d'objets légendaires",
        de = "Belohnungsleiste für legendäre Gegenstände (Saison 20)",
    },
    yule = {
        en = "Yule Festival",
        fr = "Festival de Yule",
        de = "Julfest",
    },

    -- Date-only entries from the official schedule.
    rowan_raspberry = {
        en = "Rowan Raspberry",
        fr = "Rowan Framboise",
        de = "Rowena Himbeer",
    },
    myrtle_mint = {
        en = "Myrtle Mint",
        fr = "Myrtle Menthe",
        de = "Myrtle Minz",
    },
    filbert_fig = {
        en = "Filbert Fig",
        fr = "Phillibert Fig",
        de = "Filbert Feige",
    },
};
